/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvailabilityRule {
  'id' : string,
  'slotDurationMinutes' : bigint,
  'startTime' : string,
  'endTime' : string,
  'dayOfWeek' : bigint,
  'meetingTypes' : Array<MeetingType>,
}
export interface BlockedDate {
  'id' : string,
  'date' : string,
  'reason' : [] | [string],
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'topic' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'meetingType' : MeetingType,
  'visitorName' : string,
  'visitorEmail' : string,
  'cancelReason' : [] | [string],
  'timeSlot' : TimeSlot,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'confirmed' : null };
export type MeetingType = { 'physical' : null } |
  { 'online' : null };
export interface TimeSlot { 'startTime' : string, 'endTime' : string }
export type Timestamp = bigint;
export interface _SERVICE {
  'addAvailabilityRule' : ActorMethod<
    [bigint, string, string, bigint, Array<MeetingType>],
    AvailabilityRule
  >,
  'addBlockedDate' : ActorMethod<[string, [] | [string]], BlockedDate>,
  'cancelBooking' : ActorMethod<[string, [] | [string]], boolean>,
  'createBooking' : ActorMethod<
    [string, string, string, string, TimeSlot, MeetingType],
    Booking
  >,
  'getAdmin' : ActorMethod<[], Principal>,
  'getAvailableSlots' : ActorMethod<[string, MeetingType], Array<TimeSlot>>,
  'getBooking' : ActorMethod<[string], [] | [Booking]>,
  'initializeAdmin' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listAvailabilityRules' : ActorMethod<[], Array<AvailabilityRule>>,
  'listBlockedDates' : ActorMethod<[], Array<BlockedDate>>,
  'listBookings' : ActorMethod<[], Array<Booking>>,
  'listBookingsByDate' : ActorMethod<[string], Array<Booking>>,
  'removeAvailabilityRule' : ActorMethod<[string], boolean>,
  'removeBlockedDate' : ActorMethod<[string], boolean>,
  'setAdmin' : ActorMethod<[Principal], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];