/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MeetingType = IDL.Variant({
  'physical' : IDL.Null,
  'online' : IDL.Null,
});
export const AvailabilityRule = IDL.Record({
  'id' : IDL.Text,
  'slotDurationMinutes' : IDL.Nat,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'meetingTypes' : IDL.Vec(MeetingType),
});
export const BlockedDate = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'reason' : IDL.Opt(IDL.Text),
});
export const TimeSlot = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'topic' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'meetingType' : MeetingType,
  'visitorName' : IDL.Text,
  'visitorEmail' : IDL.Text,
  'cancelReason' : IDL.Opt(IDL.Text),
  'timeSlot' : TimeSlot,
});

export const idlService = IDL.Service({
  'addAvailabilityRule' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(MeetingType)],
      [AvailabilityRule],
      [],
    ),
  'addBlockedDate' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [BlockedDate], []),
  'cancelBooking' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Bool], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, TimeSlot, MeetingType],
      [Booking],
      [],
    ),
  'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
  'getAvailableSlots' : IDL.Func(
      [IDL.Text, MeetingType],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'initializeAdmin' : IDL.Func([], [IDL.Bool], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAvailabilityRules' : IDL.Func(
      [],
      [IDL.Vec(AvailabilityRule)],
      ['query'],
    ),
  'listBlockedDates' : IDL.Func([], [IDL.Vec(BlockedDate)], ['query']),
  'listBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'listBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], []),
  'removeAvailabilityRule' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeBlockedDate' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'setAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MeetingType = IDL.Variant({
    'physical' : IDL.Null,
    'online' : IDL.Null,
  });
  const AvailabilityRule = IDL.Record({
    'id' : IDL.Text,
    'slotDurationMinutes' : IDL.Nat,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'meetingTypes' : IDL.Vec(MeetingType),
  });
  const BlockedDate = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'reason' : IDL.Opt(IDL.Text),
  });
  const TimeSlot = IDL.Record({ 'startTime' : IDL.Text, 'endTime' : IDL.Text });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'topic' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'meetingType' : MeetingType,
    'visitorName' : IDL.Text,
    'visitorEmail' : IDL.Text,
    'cancelReason' : IDL.Opt(IDL.Text),
    'timeSlot' : TimeSlot,
  });
  
  return IDL.Service({
    'addAvailabilityRule' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(MeetingType)],
        [AvailabilityRule],
        [],
      ),
    'addBlockedDate' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text)],
        [BlockedDate],
        [],
      ),
    'cancelBooking' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [IDL.Bool], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, TimeSlot, MeetingType],
        [Booking],
        [],
      ),
    'getAdmin' : IDL.Func([], [IDL.Principal], ['query']),
    'getAvailableSlots' : IDL.Func(
        [IDL.Text, MeetingType],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getBooking' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'initializeAdmin' : IDL.Func([], [IDL.Bool], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAvailabilityRules' : IDL.Func(
        [],
        [IDL.Vec(AvailabilityRule)],
        ['query'],
      ),
    'listBlockedDates' : IDL.Func([], [IDL.Vec(BlockedDate)], ['query']),
    'listBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'listBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], []),
    'removeAvailabilityRule' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeBlockedDate' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'setAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };